server:
  port: 0 #Random port, as the Sender is 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:quartzschedulerapplication
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
